server:
  port: ${PORT:8080}

spring:
  application:
    name: carDekho-ai-backend

  datasource:
    url: ${DB_URL:jdbc:mysql://reseau.proxy.rlwy.net:40413/railway}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  ai:
    openai:
      api-key: ${GROQ_API_KEY:}
      base-url: ${GROQ_BASE_URL:https://api.groq.com/openai}
      chat:
        options:
          model: ${GROQ_MODEL:llama-3.3-70b-versatile}

  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    com.carDekhoAI: INFO

cors:
  allowed-origins: ${FRONTEND_ORIGIN:http://localhost:5173}
